################################################################
# Global configuration
################################################################

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
# defaultEntryPoints = ["http", "https"]
defaultEntryPoints = ["http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":80"

[frontends]
    [frontends.frontend_manager]
    backend = "backend_manager"
        [frontends.frontend_manager.routes.routes_manager]
        rule = "Path: /version, /users, /users/{id:[0-9]+}, /tokens, /clients, /clients/{id:[0-9]+}, /channels, /channels/{id:[0,9]+}"
[backends]
    [backends.backend_manager]
        [backends.backend_manager.servers.server1]
        url = "http://localhost:8180"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]

# Web administration port
#
# Required
#
address = ":8080"

################################################################
# File configuration backend
################################################################

# Enable File configuration backend
[file]

